name: artifact_demo
on:
  push:
    branches:
      - main
      - qa
      - prod
#     paths:
#     - 'src/**'
#   pull_request:
#     branches:
#       - main
#       - qa
#       - prod
#   workflow_dispatch:
#   schedule:
#       - cron: '0 0 * * *' # Runs every day at midnight
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

        with:
          node-version: '20' # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm ci

      - name: lint code
        run: npm run lint    #its like terraform validate where it checks the code for errors or identation issues and bad practices
        
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

        with:
          node-version: '20' # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm ci

      - name: build code
        run: npm run build   #its like terraform plan where it builds the code and creates the artifacts for deployment

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-artifact
          path: dist/ #the artifact has created in this location and from here it will take and stores in the github actions server and then we can download it in the next job for deployment
          